Serilog:
  Using:
  - Serilog.Sinks.File
  MinimumLevel: Debug
  WriteTo:
  - Name: File
    Args:
      path: log.ndjson
      formatter: Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
  Enrich:
  - FromLogContext
  - WithMachineName
  - WithThreadId
  Destructure:
  - Name: ToMaximumDepth
    Args:
      maximumDestructuringDepth: 4
  - Name: ToMaximumStringLength
    Args:
      maximumStringLength: 100
  - Name: ToMaximumCollectionCount
    Args:
      maximumCollectionCount: 10
  Properties:
    Application: Probe  